CREATE DATABASE ImagineCup

USE ImagineCup

CREATE TABLE Cliente (
    ID_CLIENTE INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_IdCliente PRIMARY KEY,
    CPF INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    NASC DATE,
    EMAIL VARCHAR(50),
    FONE INT
)

CREATE TABLE Produto (
    ID_PRODUTO INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_IdProduto PRIMARY KEY,
    BARCODE INT,
    NOME VARCHAR(50) NOT NULL,
    CATEGORIA VARCHAR(20),
    PRECO FLOAT,
    QTD_ESTQ INT,
    PROMO BIT
)

CREATE TABLE Compra (
    ID_COMPRA INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_IdCompra PRIMARY KEY,
    VALOR FLOAT,
    ID_CLIENTE INT,
    CONSTRAINT fk_IdCliente FOREIGN KEY(ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE)
)

CREATE TABLE Pedido (
    ID_COMPRA INT,
    ID_PRODUTO INT,
    CONSTRAINT fk_IdCompra FOREIGN KEY(ID_COMPRA) REFERENCES Compra(ID_COMPRA),
    CONSTRAINT fk_IdProduto FOREIGN KEY(ID_PRODUTO) REFERENCES Produto(ID_PRODUTO),
    QTD INT
)

CREATE TABLE Comando (
    PALAVRA_CHAVE VARCHAR(50),
    COMANDO VARCHAR(30)
)